name: deploy static website to AWS-S3

on:
  push:
    branches:
      - 'master'
      - 'dev'
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Deploy to AWS S3 production
        # Only run for the default branch
        if: github.ref_name == 'master'
        run: |
          aws s3 sync . s3://revol-github-lab --delete

      - name: Deploy to AWS S3 development
        # Only run for the default branch
        if: github.ref_name == 'dev'
        run: |
          aws s3 sync . s3://revol-github-lab-dev --delete
